name: run tip_of_the_day.ipynb

on:
  schedule:
    - cron: '0  */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      
        - name: checkout repo content
          uses: actions/checkout@v2
          
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            
        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requitements.txt
            
        - name: execute py script
          env:
            SOME_SECRET: ${{screts.SOME_SECRET }}
          run: python tip_of_the_day.ipynb
          
        - name: commit files
        run: |
        git config --local user.email "saiyakkshit2001@gmail.com"
        git config --local user.name "saiyakkkshit"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "update logs" --allow-empty)
        
        - name: push changes
          uses: ad-m/github-push-actions@v0.6.0
          with:
          github_token: ${{ screts.GITHUB_TOKEN }}
          branch: main
